# Generated by Django 5.2.13 on 2026-04-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiduser',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfiduser',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rfiduser',
            name='rfid_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RFIDAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_code', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('granted', 'Access Granted'), ('denied', 'Access Denied')], max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('rfid_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='inventory.rfiduser')),
            ],
            options={
                'verbose_name': 'RFID Access Log',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
